In [1]:
#!pip install sodapy

# 1. Prueba de función de extracción de datos

In [2]:
#Añadimos la carpeta raiz al proyecto
import sys
import os
sys.path.append(os.path.abspath(".."))

from src.extraction import extract_socrata_data

df = extract_socrata_data(
        "izfv-6qvv",
        "../data/raw/homeris-data.csv"
)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

5000 registros descargados...
10000 registros descargados...
15000 registros descargados...
DataSet descargado correctamente y almacenado en ../data/raw/homeris-data.csv

# 2. Prueba de función de lectura csv

In [21]:
import sys
import os
sys.path.append(os.path.abspath(".."))

from src.utils import read_csv

df = read_csv("../data/raw/homeris-data.csv")

Archivo cargado existosamente desde: ../data/raw/homeris-data.csv

# 3. Analisis exploratorio

In [22]:
#Verificamos tamaño del DataSet
df.shape
#DataSet conformado por un total de 14683 filas y 7 columnas

(14683, 7)

In [23]:
#Verificamos tipos de datos
df.dtypes

anio_mes                object
municipio_residencia    object
grupo_diagnostico       object
genero_paciente         object
regimen_atencion        object
rango_edad              object
total_casos              int64
dtype: object

In [24]:
from src.cleaning import rename_columns

df = rename_columns(df)

Columnas renombradas correctamente: Index(['PERIODO', 'MUNICIPIO', 'DIAGNOSTICO', 'GENERO', 'REGIMEN',
       'RANGO_EDAD', 'CANTIDAD_CASOS'],
      dtype='object')

In [25]:
df

,PERIODO,MUNICIPIO,DIAGNOSTICO,GENERO,REGIMEN,RANGO_EDAD,CANTIDAD_CASOS
0,2024-01,ALCALA,Otros Trastornos De Ansiedad,FEMENINO,CONTRIBUTIVO,60+,1
1,2024-01,ALCALA,Problemas Relacionados Con El Grupo Primario D...,MASCULINO,SUBSIDIADO,29-59,1
2,2024-01,ALCALA,Retraso Mental Leve,MASCULINO,SUBSIDIADO,12-17,1
3,2024-01,ANSERMA,Dorsalgia,FEMENINO,SUBSIDIADO,29-59,1
4,2024-01,ANSERMA,Esquizofrenia,MASCULINO,CONTRIBUTIVO,29-59,1
...,...,...,...,...,...,...,...
14678,2024-11,VITERBO,Trastornos Delirantes Persistentes,MASCULINO,SUBSIDIADO,29-59,1
14679,2024-11,VITERBO,Trastornos Disociativos [ De Conversion ],MASCULINO,CONTRIBUTIVO,29-59,1
14680,2024-11,VITERBO,Trastornos Especificos Del Desarrollo De Las H...,MASCULINO,CONTRIBUTIVO,6-11,1
14681,2024-11,VITERBO,Trastornos Fobicos De Ansiedad,FEMENINO,CONTRIBUTIVO,29-59,1
14682,2024-11,VITERBO,Trastornos Mentales Y Del Comportamiento Debid...,FEMENINO,SUBSIDIADO,29-59,1

In [26]:
#Verificamos cantidad de nulos
df.isnull().sum()

PERIODO           0
MUNICIPIO         0
DIAGNOSTICO       0
GENERO            0
REGIMEN           0
RANGO_EDAD        0
CANTIDAD_CASOS    0
dtype: int64

In [27]:
from src.cleaning import transform_types
transform_types(df)

Columna convertida a fecha de pandas correctamente:
 PERIODO           datetime64[ns]
MUNICIPIO                 object
DIAGNOSTICO               object
GENERO                    object
REGIMEN                   object
RANGO_EDAD                object
CANTIDAD_CASOS             int64
dtype: object

,PERIODO,MUNICIPIO,DIAGNOSTICO,GENERO,REGIMEN,RANGO_EDAD,CANTIDAD_CASOS
0,2024-01-01,ALCALA,Otros Trastornos De Ansiedad,FEMENINO,CONTRIBUTIVO,60+,1
1,2024-01-01,ALCALA,Problemas Relacionados Con El Grupo Primario D...,MASCULINO,SUBSIDIADO,29-59,1
2,2024-01-01,ALCALA,Retraso Mental Leve,MASCULINO,SUBSIDIADO,12-17,1
3,2024-01-01,ANSERMA,Dorsalgia,FEMENINO,SUBSIDIADO,29-59,1
4,2024-01-01,ANSERMA,Esquizofrenia,MASCULINO,CONTRIBUTIVO,29-59,1
...,...,...,...,...,...,...,...
14678,2024-11-01,VITERBO,Trastornos Delirantes Persistentes,MASCULINO,SUBSIDIADO,29-59,1
14679,2024-11-01,VITERBO,Trastornos Disociativos [ De Conversion ],MASCULINO,CONTRIBUTIVO,29-59,1
14680,2024-11-01,VITERBO,Trastornos Especificos Del Desarrollo De Las H...,MASCULINO,CONTRIBUTIVO,6-11,1
14681,2024-11-01,VITERBO,Trastornos Fobicos De Ansiedad,FEMENINO,CONTRIBUTIVO,29-59,1
14682,2024-11-01,VITERBO,Trastornos Mentales Y Del Comportamiento Debid...,FEMENINO,SUBSIDIADO,29-59,1

In [28]:
from src.cleaning import extract_temporal_features
extract_temporal_features(df)

Variables temporales extraídas:
Index(['PERIODO', 'MUNICIPIO', 'DIAGNOSTICO', 'GENERO', 'REGIMEN',
       'RANGO_EDAD', 'CANTIDAD_CASOS', 'ANIO', 'MES_NUM', 'PERIODO_MENSUAL',
       'TRIMESTRE', 'MES_NOMBRE', 'SEMESTRE'],
      dtype='object')

,PERIODO,MUNICIPIO,DIAGNOSTICO,GENERO,REGIMEN,RANGO_EDAD,CANTIDAD_CASOS,ANIO,MES_NUM,PERIODO_MENSUAL,TRIMESTRE,MES_NOMBRE,SEMESTRE
0,2024-01-01,ALCALA,Otros Trastornos De Ansiedad,FEMENINO,CONTRIBUTIVO,60+,1,2024,1,2024-01,1,January,1
1,2024-01-01,ALCALA,Problemas Relacionados Con El Grupo Primario D...,MASCULINO,SUBSIDIADO,29-59,1,2024,1,2024-01,1,January,1
2,2024-01-01,ALCALA,Retraso Mental Leve,MASCULINO,SUBSIDIADO,12-17,1,2024,1,2024-01,1,January,1
3,2024-01-01,ANSERMA,Dorsalgia,FEMENINO,SUBSIDIADO,29-59,1,2024,1,2024-01,1,January,1
4,2024-01-01,ANSERMA,Esquizofrenia,MASCULINO,CONTRIBUTIVO,29-59,1,2024,1,2024-01,1,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14678,2024-11-01,VITERBO,Trastornos Delirantes Persistentes,MASCULINO,SUBSIDIADO,29-59,1,2024,11,2024-11,4,November,2
14679,2024-11-01,VITERBO,Trastornos Disociativos [ De Conversion ],MASCULINO,CONTRIBUTIVO,29-59,1,2024,11,2024-11,4,November,2
14680,2024-11-01,VITERBO,Trastornos Especificos Del Desarrollo De Las H...,MASCULINO,CONTRIBUTIVO,6-11,1,2024,11,2024-11,4,November,2
14681,2024-11-01,VITERBO,Trastornos Fobicos De Ansiedad,FEMENINO,CONTRIBUTIVO,29-59,1,2024,11,2024-11,4,November,2
14682,2024-11-01,VITERBO,Trastornos Mentales Y Del Comportamiento Debid...,FEMENINO,SUBSIDIADO,29-59,1,2024,11,2024-11,4,November,2

In [29]:
#Visualializar valores disponibles en las columnas

In [30]:
df.columns

Index(['PERIODO', 'MUNICIPIO', 'DIAGNOSTICO', 'GENERO', 'REGIMEN',
       'RANGO_EDAD', 'CANTIDAD_CASOS', 'ANIO', 'MES_NUM', 'PERIODO_MENSUAL',
       'TRIMESTRE', 'MES_NOMBRE', 'SEMESTRE'],
      dtype='object')

In [31]:
cols = ['MUNICIPIO', 'DIAGNOSTICO', 'GENERO', 'REGIMEN',
       'RANGO_EDAD']

for col in cols:
    print("-"*40)
    print(f"Valores disponibles en {col}")
    print(df[col].value_counts())

----------------------------------------
Valores disponibles en MUNICIPIO
MUNICIPIO
PEREIRA                5914
DOSQUEBRADAS           2528
SANTA ROSA DE CABAL    1053
LA VIRGINIA             614
BELEN DE UMBRIA         609
APIA                    372
SANTUARIO               358
GUATICA                 334
QUINCHIA                315
MARSELLA                309
VITERBO                 295
CARTAGO                 280
LA CELIA                249
MISTRATO                206
ANSERMA                 187
RISARALDA               179
BALBOA                  175
PUEBLO RICO             158
ALCALA                   91
BELALCAZAR               79
OBANDO                   50
ARMENIA                  48
ULLOA                    42
LA UNION                 37
FILANDIA                 36
ANSERMANUEVO             27
CIRCASIA                 27
MANIZALES                25
PALESTINA                13
TORO                     10
RIOSUCIO                  9
CHINCHINA                 7
LA VICTORIA               7
NEIRA                     5
EL DOVIO                  4
BOLIVAR                   3
QUIMBAYA                  3
EL CAIRO                  3
MARMATO                   3
MONTENEGRO                3
CALI                      2
SAN PABLO                 2
EL AGUILA                 2
VERSALLES                 2
MEDELLIN                  2
GUACARI                   2
ZARZAL                    1
CALARCA                   1
ANORI                     1
EL CERRITO                1
Name: count, dtype: int64
----------------------------------------
Valores disponibles en DIAGNOSTICO
DIAGNOSTICO
Otros Trastornos De Ansiedad                           1211
Trastorno Afectivo Bipolar                              990
Reaccion Al Estres Grave Y Trastornos De Adaptacion     745
Episodio Depresivo                                      656
Trastorno Depresivo Recurrente                          622
                                                       ...
Herida De La Cabeza                                       1
Otros Trastornos De Los Musculos                          1
Otras Infecciones Locales Piel Y Tejido Subcutaneo        1
Hiperplasia De La Prostata                                1
Mononeuropatias Del Miembro Superior                      1
Name: count, Length: 302, dtype: int64
----------------------------------------
Valores disponibles en GENERO
GENERO
MASCULINO    7549
FEMENINO     7134
Name: count, dtype: int64
----------------------------------------
Valores disponibles en REGIMEN
REGIMEN
SUBSIDIADO      9811
CONTRIBUTIVO    3714
OTRO            1017
PARTICULAR        79
VINCULADO         62
Name: count, dtype: int64
----------------------------------------
Valores disponibles en RANGO_EDAD
RANGO_EDAD
29-59    5132
60+      3017
18-28    2582
12-17    2442
6-11     1147
0-5       363
Name: count, dtype: int64

In [32]:
from src.cleaning import clean_diagnostico

clean_diagnostico(df)

,PERIODO,MUNICIPIO,DIAGNOSTICO,GENERO,REGIMEN,RANGO_EDAD,CANTIDAD_CASOS,ANIO,MES_NUM,PERIODO_MENSUAL,TRIMESTRE,MES_NOMBRE,SEMESTRE
0,2024-01-01,ALCALA,OTROS TRASTORNOS DE ANSIEDAD,FEMENINO,CONTRIBUTIVO,60+,1,2024,1,2024-01,1,January,1
1,2024-01-01,ALCALA,PROBLEMAS RELACIONADOS CON EL GRUPO PRIMARIO D...,MASCULINO,SUBSIDIADO,29-59,1,2024,1,2024-01,1,January,1
2,2024-01-01,ALCALA,RETRASO MENTAL LEVE,MASCULINO,SUBSIDIADO,12-17,1,2024,1,2024-01,1,January,1
3,2024-01-01,ANSERMA,DORSALGIA,FEMENINO,SUBSIDIADO,29-59,1,2024,1,2024-01,1,January,1
4,2024-01-01,ANSERMA,ESQUIZOFRENIA,MASCULINO,CONTRIBUTIVO,29-59,1,2024,1,2024-01,1,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14678,2024-11-01,VITERBO,TRASTORNOS DELIRANTES PERSISTENTES,MASCULINO,SUBSIDIADO,29-59,1,2024,11,2024-11,4,November,2
14679,2024-11-01,VITERBO,TRASTORNOS DISOCIATIVOS [ DE CONVERSION ],MASCULINO,CONTRIBUTIVO,29-59,1,2024,11,2024-11,4,November,2
14680,2024-11-01,VITERBO,TRASTORNOS ESPECIFICOS DEL DESARROLLO DE LAS H...,MASCULINO,CONTRIBUTIVO,6-11,1,2024,11,2024-11,4,November,2
14681,2024-11-01,VITERBO,TRASTORNOS FOBICOS DE ANSIEDAD,FEMENINO,CONTRIBUTIVO,29-59,1,2024,11,2024-11,4,November,2
14682,2024-11-01,VITERBO,TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...,FEMENINO,SUBSIDIADO,29-59,1,2024,11,2024-11,4,November,2

In [33]:
# Obtener valores únicos, pasarlos a mayúsculas y ordenar alfabéticamente
diagnosticos_unicos = sorted(df['DIAGNOSTICO'].unique().astype(str))

# Imprimir la lista para copiar y pegar
for diag in diagnosticos_unicos:
    print(f"'{diag}',")

'ABSCESO CUTANEO, FURUNCULO Y ANTRAX',
'ABUSO DE SUSTANCIAS QUE NO PRODUCEN DEPENDENCIA',
'ACCIDENTE VASCULAR ENCEFALICO AGUDO NO ESPECIFICADO COMO HEMORRAGICO O ISQUEMICO',
'ACNE',
'AGRESION POR EMPUJAR O COLOCAR A LA VICTIMA DELANTE DE OBJETO EN MOVIMIENTO',
'AGRESION SEXUAL CON FUERZA CORPORAL',
'ALTERACIONES DE LA SENSIBILIDAD CUTANEA',
'ALTERACIONES DEL HABLA NO CLASIFICADAS EN OTRA PARTE',
'AMIGDALITIS AGUDA',
'ANORMALIDADES DE LA MARCHA Y DE LA MOVILIDAD',
'ANORMALIDADES DE LA RESPIRACION',
'ANORMALIDADES DEL LATIDO CARDIACO',
'APORREO, GOLPE, MORDEDURA, PATADA, RASGUNO O TORCEDURA INFLIGIDOS POR OTRAS PERSONAS',
'ASMA',
'ATAQUES DE ISQUEMIA CEREBRAL TRANSITORIA Y SINDROMES AFINES',
'ATENCION PARA LA ANTICONCEPCION',
'BRONQUITIS AGUDA',
'CAIDA EN EL MISMO NIVEL POR DESLIZAMIENTO, TROPEZON O TRASPIE',
'CAIDA, SALTO O EMPUJON DESDE LUGAR ELEVADO, DE INTENCION NO DETERMINADA',
'CALCULO DEL RINON Y DEL URETER',
'CAMBIOS PERDURABLES DE LA PERSONALIDAD NO ATRIBUIBLES A LESION O A ENFERMEDAD CEREBRAL',
'CANDIDIASIS',
'CARIES DENTAL',
'CEFALEA',
'CELULITIS',
'COLICO RENAL NO ESPECIFICADO',
'CONSULTA RELACIONADA CON ACTITUD, CONDUCTA U ORIENTACION SEXUAL',
'CONTROL GENERAL DE SALUD DE RUTINA DE SUBPOBLACIONES DEFINIDAS',
'CONVULSIONES NO CLASIFICADAS EN OTRA PARTE',
'COXARTROSIS',
'DELIRIO, NO INDUCIDO POR EL ALCOHOL O POR OTRAS SUSTANCIAS PSICOACTIVAS',
'DEMENCIA EN LA ENFERMEDAD DE ALZHEIMER',
'DEMENCIA EN OTRAS ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
'DEMENCIA NO ESPECIFICADA',
'DERMATITIS ATOPICA',
'DERMATITIS SEBORREICA',
'DERMATOFITOSIS',
'DESNUTRICION PROTEICOCALORICA NO ESPECIFICADA',
'DIABETES MELLITUS INSULINODEPENDIENTE',
'DIABETES MELLITUS NO INSULINODEPENDIENTE',
'DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN INFECCIOSO',
'DISFUNCION SEXUAL NO OCASIONADA POR TRASTORNOS NI ENFERMEDADES ORGANICOS',
'DISLEXIA Y OTRAS DISFUNCIONES SIMBOLICAS NO CLASIFICADAS EN OTRA PARTE',
'DISPEPSIA',
'DISTONIA',
'DOLOR ABDOMINAL Y PELVICO',
'DOLOR DE GARGANTA Y EN EL PECHO',
'DOLOR NO CLASIFICADAS EN OTRA PARTE',
'DOLOR Y OTRAS AFECCIONES RELACIONADAS CON LOS ORGANOS GENITALES FEMENINOS Y CON EL CICLO MENSTRUAL',
'DORSALGIA',
'EFECTO TOXICO DE OTRAS SUSTANCIAS Y LAS NO ESPECIFICADAS',
'EFECTO TOXICO DE PLAGUICIDAS [PESTICIDAS]',
'EFECTOS ADVERSOS DE DROGAS PSICOTROPICAS NO CLASIFICADAS EN OTRA PARTE',
'EFECTOS ADVERSOS DE DROGAS SEDANTES, HIPNOTICAS Y ANSIOLITICAS',
'EFECTOS ADVERSOS NO CLASIFICADOS EN OTRA PARTE',
'EMBARAZO ECTOPICO',
'ENCEFALOPATIA TOXICA',
'ENFERMEDAD DE ALZHEIMER',
'ENFERMEDAD DE HUNTINGTON',
'ENFERMEDAD DE PARKINSON',
'ENFERMEDAD DEL REFLUJO GASTROESOFAGICO',
'ENFERMEDAD POR VIRUS DE LA INMUNODEFICIENCIA HUMANA [ VIH ],',
'ENFERMEDAD POR VIRUS DE LA INMUNODEFICIENCIA HUMANA [ VIH ], SIN OTRA ESPECIFICACION',
'ENVENENAMIENTO AUTOINFLINGIDO INTENCIONALMENTE POR, Y EXPOSICION A ANALGESICOS NO NARCOTICOS, ANTIPIRETICOS Y ANTIRREUMATICOS',
'ENVENENAMIENTO AUTOINFLINGIDO INTENCIONALMENTE POR, Y EXPOSICION A DROGAS ANTIEPILEPTICAS, SEDANTES, HIPNOTICAS, ANTIPARINSONIANAS Y PSICOTROPICAS, NO CLASIFICADAS EN OTRA PARTE',
'ENVENENAMIENTO AUTOINFLINGIDO INTENCIONALMENTE POR, Y EXPOSICION A OTRAS DROGAS, MEDICAMENTOS Y SUSTANCIAS BIOLOGICAS Y LOS NO ESPECIFICADOS',
'ENVENENAMIENTO AUTOINFLINGIDO INTENCIONALMENTE POR, Y EXPOSICION A OTROS PRODUCTOS QUIMICOS Y SUSTANCIAS NOCIVAS Y LOS NO ESPECIFICADOS',
'ENVENENAMIENTO AUTOINFLINGIDO INTENCIONALMENTE POR, Y EXPOSICION A PLAGUICIDAS',
'EPILEPSIA',
'EPISODIO DEPRESIVO',
'EPISODIO MANIACO',
'ESCABIOSIS',
'ESCOLIOSIS',
'ESQUIZOFRENIA',
'ESQUIZOFRENIA RESIDUAL',
'ESTADO DE INFECCION ASINTOMATICA POR EL VIRUS DE LA INMUNODEFICIENCIA HUMANA [ VIH ]',
'ESTADO DE MAL EPILEPTICO',
'ESTOMATITIS Y LESIONES AFINES',
'EXAMEN DE PESQUISA ESPECIAL PARA ENFERMEDADES INFECCIOSAS Y PARASITARIAS',
'EXAMEN DE PESQUISA ESPECIAL PARA OTRAS ENFERMEDADES Y TRASTORNOS',
'EXAMEN GENERAL E INVESTIGACION DE PERSONAS SIN QUEJAS O SIN DIAGNOSTICO INFORMADO',
'EXAMEN Y OBSERVACION POR OTRAS RAZONES',
'EXAMEN Y PRUEBA DEL EMBARAZO',
'FACOMATOSIS NO CLASIFICADAS EN OTRA PARTE',
'FALTA DEL DESARROLLO FISIOLOGICO NORMAL ESPERADO',
'FIEBRES RECURRENTES',
'FLEBITIS Y TROMBOFLEBITIS',
'FRACTURA PIERNA, INCLUSIVE EL TOBILLO',
'GASTRITIS Y DUODENITIS',
'GINGIVITIS Y ENFERMEDADES PERIODONTALES',
'HEMIPLEJIA',
'HERIDA DE LA CABEZA',
'HERIDA DE LA PIERNA',
'HERNIA INGUINAL',
'HERPES ZOSTER',
'HIPERPLASIA DE LA PROSTATA',
'HIPERTENSION ESENCIAL (PRIMARIA)',
'HIPOACUSIA CONDUCTIVA Y NEUROSENSORIAL',
'HIPOTENSION',
'HISTORIA FAMILIAR DE CIERTAS DISCAPACIDADES Y ENFERMEDADES CRONICAS INCAPACITANTES',
'HISTORIA FAMILIAR DE TRASTORNOS MENTALES Y DE COMPORTAMIENTO',
'HISTORIA PERSONAL DE ALGUNAS OTRAS ENFERMEDADES',
'HISTORIA PERSONAL DE FACTORES DE RIESGO NO CLASIFICADAS EN OTRA PARTE',
'INCONTINENCIA FECAL',
'INCONTINENCIA URINARIA NO ESPECIFICADA',
'INFARTO AGUDO DEL MIOCARDIO',
'INFECCIONES DEBIDAS A OTRAS MICOBACTERIAS',
'INFECCIONES INTESTINALES DEBIDAS A VIRUS Y OTROS ORGANISMOS ESPECIFICADOS',
'INFECION ANOGENITAL DEBIDA A VIRUS DEL HERPES [HERPES SIMPLE ]',
'INFLUENZA DEBIDA A VIRUS NO IDENTIFICADO',
'INMUNODEFICIENCIAS ASOCIADAS A OTROS DEFECTOS MAYORES',
'INSUFICIENCIA RENAL CRONICA',
'INSUFICIENCIA RENAL NO ESPECIFICADA',
'LESION AUTOINFLINGIDA INTENCIONALMENTE POR AHORCAMIENTO, ESTRANGULAMIENTO O SOFOCACION',
'LESION AUTOINFLINGIDA INTENCIONALMENTE POR OBJETO CORTANTE',
'LESION AUTOINFLINGIDA INTENCIONALMENTE POR OBJETO ROMO O SIN FILO',
'LUPUS ERITEMATOSO',
'LUXACION, ESGUINCE Y TORCEDURA DE ARTICULACIONES Y LIGAMENTOS DEL TOBILLO Y DEL PIE',
'MALESTAR Y FATIGA',
'MAREO Y DESVANECIMIENTO',
'MIGRANA',
'MONONEUROPATIAS DEL MIEMBRO INFERIOR',
'MONONEUROPATIAS DEL MIEMBRO SUPERIOR',
'MOVIMIENTOS INVOLUNTARIOS ANORMALES',
'NAUSEA Y VOMITO',
'NEGLIGENCIA Y ABANDONO',
'NEUMONIA BACTERIANA NO CLASIFICADA EN OTRA PARTE',
'NEUMONIA ORGANISMO NO ESPECIFICADO',
'OBESIDAD',
'OBSERVACION Y EVALUACION MEDICAS POR SOSPECHA DE ENFERMEDADES Y AFECCIONES',
'OSTEOPOROSIS CON FRACTURA PATOLOGICA',
'OTITIS EXTERNA',
'OTITIS MEDIA NO SUPURATIVA',
'OTRAS ANOMALIAS CROMOSOMICAS NO CLASIFICADAS EN OTRA PARTE',
'OTRAS DEFORMIDADES ADQUIRIDAS DE LOS MIEMBROS',
'OTRAS DORSOPATIAS DEFORMANTES',
'OTRAS ENFERMEDADES CEREBROVASCULARES',
'OTRAS ENFERMEDADES DE TRANSMISION SEXUAL DEBIDADAS A CLAMIDIAS',
'OTRAS ENFERMEDADES DEGENERATIVAS DEL SISTEMA NERVIOSO NO CLASIFICADAS EN OTRA PARTE',
'OTRAS ENFERMEDADES DEL ESOFAGO',
'OTRAS ENFERMEDADES INFLAMATORIAS DE LA VAGINA Y DE LA VULVA',
'OTRAS ENFERMEDADES PELVICAS INFLAMATORIAS FEMENINAS',
'OTRAS ENFERMEDADES PULMONARES OBSTRUCTIVAS CRONICAS',
'OTRAS ENTESOPATIAS',
'OTRAS HIPOACUSIAS',
'OTRAS INFECCIONES LOCALES PIEL Y TEJIDO SUBCUTANEO',
'OTRAS MALFORMACIONES CONGENITAS DEL INTESTINO',
'OTRAS MICOSIS SUPERFICIALES',
'OTRAS SIFILIS Y LAS NO ESPECIFICADAS',
'OTRAS TRISOMIAS Y TRISOMIAS PARCIALES DE LOS AUTOSOMAS NO CLASIFICADAS EN OTRA PARTE',
'OTROS EXAMENES ESPECIALES PERSONAS SIN QUEJAS O SIN DIAGNOSTICO INFORMADO',
'OTROS HIPOTIROIDISMOS',
'OTROS PROBLEMAS RELACIONADOS CON LA CRIANZA DEL NINO',
'OTROS SINDROMES DE CEFALEA',
'OTROS SINDROMES DE MALTRATO',
'OTROS SINTOMAS Y SIGNOS GENERALES',
'OTROS SINTOMAS Y SIGNOS QUE INVOLUCRAN LA FUNCION COGNOSCITIVA Y LA CONCIENCIA',
'OTROS SINTOMAS Y SIGNOS QUE INVOLUCRAN LAS SENSACIONES Y PERCEPCIONES GENERALES',
'OTROS TIPOS DE RETRASO MENTAL',
'OTROS TRASTORNOS ARTICULARES NO CLASIFICADAS EN OTRA PARTE',
'OTROS TRASTORNOS DE ANSIEDAD',
'OTROS TRASTORNOS DE LA PERSONALIDAD Y DEL COMPORTAMIENTO EN ADULTOS',
'OTROS TRASTORNOS DE LOS DISCOS INTERVERTEBRALES',
'OTROS TRASTORNOS DE LOS MUSCULOS',
'OTROS TRASTORNOS DE LOS PARPADOS',
'OTROS TRASTORNOS DE LOS TEJIDOS BLANDOS NO CLASIFICADOS EN OTRA PARTE',
'OTROS TRASTORNOS DEGENERATIVOS DEL SISTEMA NERVIOSO EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
'OTROS TRASTORNOS DEL DESARROLLO PSICOLOGICO',
'OTROS TRASTORNOS DEL HUMOR [ AFECTIVOS ]',
'OTROS TRASTORNOS DEL METABOLISMO DE LOS CARBOHIDRATOS',
'OTROS TRASTORNOS DEL OIDO INTERNO',
'OTROS TRASTORNOS DEL OJO Y SUS ANEXOS EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
'OTROS TRASTORNOS DEL SISTEMA URINARIO',
'OTROS TRASTORNOS EMOCIONALES Y DEL COMPORTAMIENTO QUE APARECEN HABITUALMENTE EN LA NINEZ Y EN LA ADOLESCENCIA',
'OTROS TRASTORNOS EXTRAPIRAMIDALES Y DEL MOVIMIENTO',
'OTROS TRASTORNOS FUNCIONALES DEL INTESTINO',
'OTROS TRASTORNOS MENOPAUSICOS Y PERIMENOPAUSICOS',
'OTROS TRASTORNOS MENTALES DEBIDOS A LESION Y DISFUNCION CEREBRAL, Y A ENFERMEDAD FISICA',
'OTROS TRASTORNOS NEUROTICOS',
'OTROS TRASTORNOS PSICOTICOS DE ORIGEN NO ORGANICO',
'OTROS TRASTORNOS TIROIDEOS',
'OTROS TRAUMATISMO Y LOS NO ESPECIFICADOS DE CABEZA',
'OTROS TRAUMATISMOS DE MIEMBRO INFERIOR, NIVEL NO ESPECIFICADO',
'PARALISIS CEREBRAL',
'PEDICULOSIS Y PHTHIRIASIS',
'PERSONA EN CONTACTO CON LOS SERVICIOS DE SALUD POR OTRAS CIRCUNSTANCIAS',
'PERSONA EN CONTACTO CON LOS SERVICIOS DE SALUD POR OTRAS CONSULTAS Y CONSEJOS MEDICOS, NO CLASIFICADOS EN OTRA PARTE',
'PROBLEMAS RELACIONADOS CON DIFICULTADES CON EL MODO DE VIDA',
'PROBLEMAS RELACIONADOS CON EL AMBIENTE SOCIAL',
'PROBLEMAS RELACIONADOS CON EL EMPLEO Y EL DESEMPLEO',
'PROBLEMAS RELACIONADOS CON EL ESTILO DE VIDA',
'PROBLEMAS RELACIONADOS CON EL GRUPO PRIMARIO DE APOYO, INCLUSIVE CIRCUNSTANCIAS FAMILIARES',
'PROBLEMAS RELACIONADOS CON FACILIDADES DE ATENCION MEDICA U OTROS SERVICIOS DE SALUD',
'PROBLEMAS RELACIONADOS CON HECHOS NEGATIVOS EN LA NINEZ',
'PROBLEMAS RELACIONADOS CON LA EDUCACION Y LA ALFABETIZACION',
'PROBLEMAS RELACIONADOS CON LA VIVIENDA Y LAS CIRCUNSTANCIAS ECONOMICAS',
'PROBLEMAS RELACIONADOS CON OTRAS CIRCUNSTANCIAS PSICOSOCIALES',
'PRURITO',
'PSICOSIS DE ORIGEN NO ORGANICO, NO ESPECIFICADA',
'PURPURA Y OTRAS AFECCIONES HEMORRAGICAS',
'QUEMADURAS CLASIFICADAS SEGUN LA EXTENSION DE LA SUPERFICIE DEL CUERPO AFECTADA',
'REACCION AL ESTRES GRAVE Y TRASTORNOS DE ADAPTACION',
'RETARDO DEL DESARROLLO DEBIDAS A DESNUTRICION PROTEICOCALORICA',
'RETENCION DE ORINA',
'RETRASO MENTAL GRAVE',
'RETRASO MENTAL LEVE',
'RETRASO MENTAL MODERADO',
'RETRASO MENTAL NO ESPECIFICADO',
'RETRASO MENTAL PROFUNDO',
'RINOFARINGITIS AGUDA',
'RUPTURA PREMATURA DE LAS MEMBRANAS',
'SECUELAS DE ACCIDENTE DE TRANSPORTE',
'SECUELAS DE ENFERMEDADES CEREBROVASCULAR',
'SECUELAS DE ENFERMEDADES INFLAMATORIAS DEL SISTEMA NERVIOSO CENTRAL',
'SECUELAS DE OTRAS ENFERMEDADES INFECCIOSAS Y PARASITARIAS Y DE LAS NO ESPECIFICADAS',
'SECUELAS DE TRAUMATISMOS DE LA CABEZA',
'SECUELAS DE TRAUMATISMOS DEL CUELLO Y DEL TRONCO',
'SIFILIS TARDIA',
'SINCOPE Y COLAPSO',
'SINDROME DE DOWN',
'SINDROME DEL COLON IRRITABLE',
'SINDROME DEL COMPORTAMIENTO ASOCIADOS CON ALTERACIONES FISIOLOGICAS Y FACTORES FISICOS NO ESPECIFICADOS',
'SINDROMES DEL MALTRATO',
'SINDROMES VASCULARES ENCEFALICOS EN ENFERMEDADES CEREBROVASCULARES',
'SINOVITIS Y TENOSINOVITIS',
'SINTOMAS Y SIGNOS QUE INVOLUCRAN CONCERNIENTES A LA ALIMENTACION E INGESTION DE LIQUIDOS',
'SINTOMAS Y SIGNOS QUE INVOLUCRAN EL ESTADO EMOCIONAL',
'SINTOMAS Y SIGNOS QUE INVOLUCRAN LA APARIENCIA Y EL COMPORTAMIENTO',
'SINUSITIS AGUDA',
'SINUSITIS CRONICA',
'SUPERVISION DE EMBARAZO DE ALTO RIESGO',
'SUPERVISION DE EMBARAZO NORMAL',
'TRASTORNO AFECTIVO BIPOLAR',
'TRASTORNO DE LA PERSONALIDAD Y DEL COMPORTAMIENTO EN ADULTOS, NO ESPECIFICADO',
'TRASTORNO DEL HUMOR [ AFECTIVO ], NO ESPECIFICADO',
'TRASTORNO DEPRESIVO RECURRENTE',
'TRASTORNO ESQUIZOTIPICO',
'TRASTORNO INTERNO DE LA RODILLA',
'TRASTORNO MENTAL NO ESPECIFICADO',
'TRASTORNO MENTAL ORGANICO O SINTOMATICO, NO ESPECIFICADO',
'TRASTORNO OBSESIVO-COMPULSIVO',
'TRASTORNOS ADRENOGENITALES',
'TRASTORNOS DE LA CONDUCTA',
'TRASTORNOS DE LA IDENTIDAD DE GENERO',
'TRASTORNOS DE LA INGESTION DE ALIMENTOS',
'TRASTORNOS DE LA PERSONALIDAD Y DEL COMPORTAMIENTO DEBIDOS A ENFERMEDAD, LESION O DISFUNCION CEREBRAL',
'TRASTORNOS DE LA PREFERENCIA SEXUAL',
'TRASTORNOS DE LAS RAICES Y DE LOS PLEXOS NERVIOSOS',
'TRASTORNOS DE LAS UNAS',
'TRASTORNOS DE LOS HABITOS Y DE LOS IMPULSOS',
'TRASTORNOS DE LOS ORGANOS GENITALES MASCULINOS EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
'TRASTORNOS DEL COMPORTAMIENTO SOCIAL DE COMIENZO ESPECIFICO EN LA NINEZ Y EN LA ADOLESCENCIA',
'TRASTORNOS DEL DISCO CERVICAL',
'TRASTORNOS DEL HUMOR [ AFECTIVOS ] PERSISTENTES',
'TRASTORNOS DEL METABOLISMO DE LAS PORFIRINAS Y DE LA BILIRRUBINA',
'TRASTORNOS DEL SUENO',
'TRASTORNOS DELIRANTES PERSISTENTES',
'TRASTORNOS DISOCIATIVOS [ DE CONVERSION ]',
'TRASTORNOS EMOCIONALES COMIENZO ESPECIFICO EN LA NINEZ',
'TRASTORNOS ESPECIFICOS DE LA PERSONALIDAD',
'TRASTORNOS ESPECIFICOS DEL DESARROLLO DE LAS HABILIDADES ESCOLARES',
'TRASTORNOS ESPECIFICOS DEL DESARROLLO DEL HABLA Y DEL LENGUAJE',
'TRASTORNOS ESPECIFICOS MIXTOS DESARROLLO',
'TRASTORNOS ESQUIZOAFECTANIVOS',
'TRASTORNOS FOBICOS DE ANSIEDAD',
'TRASTORNOS GENERALIZADOS DEL DESARROLLO',
'TRASTORNOS HIPERCINETICOS',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO ASOCIADOS AL PUERPERIO NO CLASIFICADOS EN OTRA PARTE',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE ALUCINOGENOS',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE CANNABINOIDES',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE COCAINA',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE DISOLVENTES VOLATILES',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE MULTIPLES DROGAS Y AL USO DE OTRAS SUSTANCIAS PSICOACTIVAS',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE OPIACEOS',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE OTROS ESTIMULANTES',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DE SEDANTES O HIPNOTICOS',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DEL ALCOHOL',
'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL USO DEL TABACO',
'TRASTORNOS MIXTOS DE LA CONDUCTA Y DE LAS EMOCIONES',
'TRASTORNOS MIXTOS Y OTROS TRASTORNOS DE LA PERSONALIDAD',
'TRASTORNOS MUSCULARES PRIMARIOS',
'TRASTORNOS NO ORGANICOS DEL SUENO',
'TRASTORNOS POR TICS',
'TRASTORNOS PSICOLOGICOS Y DEL COMPORTAMIENTO ASOCIADOS CON EL DESARROLLO Y CON LA ORIENTACION SEXUALES',
'TRASTORNOS PSICOTICOS AGUDOS Y TRANSITORIOS',
'TRASTORNOS SOMATOMORFOS',
'TRAUMATISMO DE NERVIOS Y DE LA MEDULA ESPINAL A NIVEL DE TORAX',
'TRAUMATISMO INTRACRANEAL',
'TRAUMATISMO SUPERFICIAL DE LA CABEZA',
'TRAUMATISMO SUPERFICIAL DE LA MUNECA Y DE LA MANO',
'TRAUMATISMO SUPERFICIAL DE LA PIERNA',
'TRAUMATISMO SUPERFICIAL DEL HOMBRO Y DEL BRAZO',
'TRAUMATISMO SUPERFICIAL DEL TOBILLO Y DEL PIE',
'TRAUMATISMO SUPERFICIAL DEL TORAX',
'TUBERCULOSIS RESPIRATORIA, CONFIRMADA BACTERIOLOGICA E HISTOLOGICAMENTE',
'TUMOR BENIGNO DE LA GLANDULA TIROIDES',
'TUMOR DE COMPORTAMIENTO INCIERTO DEL ENCEFALO Y DEL SISTEMA NERVIOSO CENTRAL',
'TUMOR DE COMPORTAMIENTO INCIERTO O DESCONOCIDO DE OTROS SITIOS Y DE LOS NO ESPECIFICADOS',
'ULCERACION E INFLAMACION VULVOVAGINAL EN ENFERMEDADES CLASIFICADAS EN OTRA PARTE',
'URTICARIA',
'VARICES DE OTROS SITIOS',
'VENAS VARICOSAS DE LOS MIEMBROS INFERIORES',

In [34]:
from src.cleaning import mapeo_diagnostico, clasificar_diagnostico, sep_salud_mental

clasificar_diagnostico(df)
sep_salud_mental(df)

Diagnóstico clasificado correctamente:
 0              SALUD_MENTAL
1         FACTORES_SOCIALES
2              SALUD_MENTAL
3        MUSCULOESQUELETICO
4              SALUD_MENTAL
                ...
14678          SALUD_MENTAL
14679          SALUD_MENTAL
14680          SALUD_MENTAL
14681          SALUD_MENTAL
14682          SALUD_MENTAL
Name: GRUPO_DIAGNOSTICO, Length: 14683, dtype: object

In [35]:
df_filtro = df[df['GRUPO_DIAGNOSTICO'] == "OTROS"]
df_filtro['DIAGNOSTICO'].value_counts()

DIAGNOSTICO
DISFUNCION SEXUAL NO OCASIONADA POR TRASTORNOS NI ENFERMEDADES ORGANICOS    18
DISLEXIA Y OTRAS DISFUNCIONES SIMBOLICAS NO CLASIFICADAS EN OTRA PARTE       3
ABUSO DE SUSTANCIAS QUE NO PRODUCEN DEPENDENCIA                              1
ESTADO DE MAL EPILEPTICO                                                     1
LUPUS ERITEMATOSO                                                            1
Name: count, dtype: int64

In [36]:
df['GRUPO_DIAGNOSTICO'].value_counts()

GRUPO_DIAGNOSTICO
SALUD_MENTAL                 11709
FACTORES_SOCIALES              691
SINTOMAS_GENERALES             638
CONTACTO_SERVICIOS_SALUD       478
NEUROLOGICO                    405
TRAUMA_ACCIDENTES              163
ENDOCRINO_METABOLICO           113
DIGESTIVO                       93
CARDIOVASCULAR                  74
INFECTOLOGIA                    68
PIEL                            66
MUSCULOESQUELETICO              51
GENITOURINARIO                  39
MALFORMACIONES_CONGENITAS       34
OTROS                           24
EMBARAZO                        16
RESPIRATORIO                    10
INTOXICACIONES                  10
TUMORES                          1
Name: count, dtype: int64

In [37]:
df

,PERIODO,MUNICIPIO,DIAGNOSTICO,GENERO,REGIMEN,RANGO_EDAD,CANTIDAD_CASOS,ANIO,MES_NUM,PERIODO_MENSUAL,TRIMESTRE,MES_NOMBRE,SEMESTRE,GRUPO_DIAGNOSTICO,SALUD_MENTAL_CLASS
0,2024-01-01,ALCALA,OTROS TRASTORNOS DE ANSIEDAD,FEMENINO,CONTRIBUTIVO,60+,1,2024,1,2024-01,1,January,1,SALUD_MENTAL,SALUD_MENTAL
1,2024-01-01,ALCALA,PROBLEMAS RELACIONADOS CON EL GRUPO PRIMARIO D...,MASCULINO,SUBSIDIADO,29-59,1,2024,1,2024-01,1,January,1,FACTORES_SOCIALES,OTROS_GRUPOS_DX
2,2024-01-01,ALCALA,RETRASO MENTAL LEVE,MASCULINO,SUBSIDIADO,12-17,1,2024,1,2024-01,1,January,1,SALUD_MENTAL,SALUD_MENTAL
3,2024-01-01,ANSERMA,DORSALGIA,FEMENINO,SUBSIDIADO,29-59,1,2024,1,2024-01,1,January,1,MUSCULOESQUELETICO,OTROS_GRUPOS_DX
4,2024-01-01,ANSERMA,ESQUIZOFRENIA,MASCULINO,CONTRIBUTIVO,29-59,1,2024,1,2024-01,1,January,1,SALUD_MENTAL,SALUD_MENTAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14678,2024-11-01,VITERBO,TRASTORNOS DELIRANTES PERSISTENTES,MASCULINO,SUBSIDIADO,29-59,1,2024,11,2024-11,4,November,2,SALUD_MENTAL,SALUD_MENTAL
14679,2024-11-01,VITERBO,TRASTORNOS DISOCIATIVOS [ DE CONVERSION ],MASCULINO,CONTRIBUTIVO,29-59,1,2024,11,2024-11,4,November,2,SALUD_MENTAL,SALUD_MENTAL
14680,2024-11-01,VITERBO,TRASTORNOS ESPECIFICOS DEL DESARROLLO DE LAS H...,MASCULINO,CONTRIBUTIVO,6-11,1,2024,11,2024-11,4,November,2,SALUD_MENTAL,SALUD_MENTAL
14681,2024-11-01,VITERBO,TRASTORNOS FOBICOS DE ANSIEDAD,FEMENINO,CONTRIBUTIVO,29-59,1,2024,11,2024-11,4,November,2,SALUD_MENTAL,SALUD_MENTAL
14682,2024-11-01,VITERBO,TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...,FEMENINO,SUBSIDIADO,29-59,1,2024,11,2024-11,4,November,2,SALUD_MENTAL,SALUD_MENTAL

In [38]:
print(df["GRUPO_DIAGNOSTICO"].value_counts())

GRUPO_DIAGNOSTICO
SALUD_MENTAL                 11709
FACTORES_SOCIALES              691
SINTOMAS_GENERALES             638
CONTACTO_SERVICIOS_SALUD       478
NEUROLOGICO                    405
TRAUMA_ACCIDENTES              163
ENDOCRINO_METABOLICO           113
DIGESTIVO                       93
CARDIOVASCULAR                  74
INFECTOLOGIA                    68
PIEL                            66
MUSCULOESQUELETICO              51
GENITOURINARIO                  39
MALFORMACIONES_CONGENITAS       34
OTROS                           24
EMBARAZO                        16
RESPIRATORIO                    10
INTOXICACIONES                  10
TUMORES                          1
Name: count, dtype: int64